--- #YAML:1.0
name:               DateTime-Format-Perl6
version:            v1.0.0
abstract:           Parse and format Perl6-style datetime strings
author:
    - Eric Brine <ikegami@adaelis.com>
    - Timothy Totten <supernovus@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:    0
    Test::More:  0
    version:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
